coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "examples/**"
  - "deps/**"
  - "test/**"
  - ".zig-cache/**"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
